### ISSUE TITLE
Join users gives error: DiscordAPIError: Invalid Form Body

### ISSUE THREAD

**Issue by subjoel** [iLxlo/discord-oauth-bot#4]
when i try the join users command, it gives me this error:
```
2023-09-23T14:21:47.013 app[080e327a6636d8] mad [info] Unhandled rejection: DiscordAPIError[50035]: Invalid Form Body

2023-09-23T14:21:47.013 app[080e327a6636d8] mad [info] data.components[0].components[0].options[1][SELECT_COMPONENT_OPTION_VALUE_DUPLICATED]: The specified option value is already used

2023-09-23T14:21:47.013 app[080e327a6636d8] mad [info] at handleErrors (/app/node_modules/@discordjs/rest/dist/index.js:687:13)

2023-09-23T14:21:47.013 app[080e327a6636d8] mad [info] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

2023-09-23T14:21:47.013 app[080e327a6636d8] mad [info] at async BurstHandler.runRequest (/app/node_modules/@discordjs/rest/dist/index.js:786:23)

2023-09-23T14:21:47.013 app[080e327a6636d8] mad [info] at async _REST.request (/app/node_modules/@discordjs/rest/dist/index.js:1218:22)

2023-09-23T14:21:47.013 app[080e327a6636d8] mad [info] at async StringSelectMenuInteraction.update (/app/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:233:5)

2023-09-23T14:21:47.054 app[48ed034c1e7238] mad [info] Unhandled rejection: DiscordAPIError[50035]: Invalid Form Body

2023-09-23T14:21:47.054 app[48ed034c1e7238] mad [info] data.components[0].components[0].options[1][SELECT_COMPONENT_OPTION_VALUE_DUPLICATED]: The specified option value is already used

2023-09-23T14:21:47.054 app[48ed034c1e7238] mad [info] at handleErrors (/app/node_modules/@discordjs/rest/dist/index.js:687:13)

2023-09-23T14:21:47.054 app[48ed034c1e7238] mad [info] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

2023-09-23T14:21:47.054 app[48ed034c1e7238] mad [info] at async BurstHandler.runRequest (/app/node_modules/@discordjs/rest/dist/index.js:786:23)

2023-09-23T14:21:47.054 app[48ed034c1e7238] mad [info] at async _REST.request (/app/node_modules/@discordjs/rest/dist/index.js:1218:22)

2023-09-23T14:21:47.054 app[48ed034c1e7238] mad [info] at async StringSelectMenuInteraction.update (/app/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:233:5)
```

**Comment by subjoel** [comment]
also the auto join server command doesnt work

**Comment by subjoel** [comment]
UPDATE!
fixed it, i found out i was running the bot on 2 servers so the authorized server id got added 2x. wich caused the discord form to have 2 fields with same server name.

**Comment by iLxlo** [comment]
💪
